### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by JeanPerriault** [vcl/doc#11]
Hi,
Just ending up with this error when running tutorial step 5 (`node ./node_modules/.bin/vcl-preprocessor index.styl vcl.css`):

```
$ node ./node_modules/.bin/vcl-preprocessor index.styl vcl.css
C:\Users\XXXX\Workspace\vcl\doc\tutorial\node_modules\.bin\vcl-preprocessor:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```
Same error using vcl-preprocessor -h or -v options
Using node 5.10.1 and npm 3.8.6

**Comment by vanthome** [comment]
I have updated the tutorial docs, to make it more compatible with the windows platform. You can also run this command w/o which would work under windows: `node_modules\.bin\vcl-preprocessor.cmd index.styl vcl.css`

**Comment by JeanPerriault** [comment]
No more errors with those tricks (vcl-preprocessor global install or call to .cmd file), but now it's hanging indefinitely without any information.
I first suspected windows wrappers issues, or missing permissions, but it is made the same way other modules like bower.
So I tried calling directly vcl.js with verbose option I got that:

```
$ node node_modules/vcl-preprocessor/bin/vcl.js index.html vcl.css --verbose
C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\css\lib\parse\index.js:72
      throw err;
      ^

Error: C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\index.html:13:9: missing '{'
    at error (C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\css\lib\parse\index.js:62:15)
    at declarations (C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\css\lib\parse\index.js:247:25)
    at rule (C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\css\lib\parse\index.js:560:21)
    at rules (C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\css\lib\parse\index.js:117:70)
    at stylesheet (C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\css\lib\parse\index.js:81:21)
    at module.exports (C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\css\lib\parse\index.js:564:20)
    at rework (C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\rework\index.js:27:21)
    at new Processor (C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\vcl-preprocessor\index.js:30:18)
    at cProcessor (C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\vcl-preprocessor\index.js:63:10)
    at compile (C:\Users\E8001289\Workspace\2_UI_sandbox\vcl\doc\tutorial\node_modules\vcl-preprocessor\bin\vcl.js:20:18)

```

**Comment by vanthome** [comment]
This is just wrong usage, you should run:

```
$ node node_modules/vcl-preprocessor/bin/vcl.js index.stly vcl.css --verbose
```

instead.

**Comment by JeanPerriault** [comment]
Oh yes sorry, thx for input. Just one typo in your line, _index.stly_ shoud be _index.**styl**_. Then it works great
